### ISSUE TITLE
Typo in repository descrption

### ISSUE THREAD

**Issue by chengluyu** [LZKSKY/DataMining-2019#1]
![image](https://user-images.githubusercontent.com/2239547/65338660-4279d400-dbfd-11e9-8f4a-ed65691f077f.png)

Should be "is" instead of "it".

**Comment by LZKSKY** [comment]
Of course. While, I can not find how to modify discription in Settings last time, may be in somewhere else.

**Comment by chengluyu** [comment]
Hint: you can set it in repository homepage.
![image](https://user-images.githubusercontent.com/2239547/65372718-22521f80-dca6-11e9-923e-5515e49bb9ba.png)

**Comment by chengluyu** [comment]
By the way, there is another typo in your reply.
![image](https://user-images.githubusercontent.com/2239547/65372728-3b5ad080-dca6-11e9-9f0b-2b7a52f5bef9.png)
